language: python
python:
  - "3.8"
services:
  - docker
install:
  - ./scripts/setup.sh
script:
  - ./scripts/test.sh
  - ./scripts/lint.sh
  - ./scripts/build_docker.sh
  - ./scripts/test_docker.sh
  - ./scripts/deploy.sh --test
deploy:
  # package and publish the library to pypi repository
  - provider: script
    script: ./scripts/deploy.sh
    on:
      tags: true
env:
  global:
    - PYPI_USERNAME='__token__'
    # PYPI_TOKEN
    - secure: "qG/M3WKKD19G74w62qR3Kne6eO9kmZOOSEtHg3kFPIqSLIJot+I3n0Y+zqOeVfPJI8kvB6mibu290HEkdaJyJS7J3/QVPUJINFl7hfikzmVhXo+Cc4OCTLt50ydykkARbI46DmsuOG7H1vLuQVnnLVKE/OkbiAGyQccq97eCgOsw3DzpVxxzsgFbOOaB7H1vZWNE1K6xA8XhWke/M3kZTUOd1YpLZWeLovGbHNngAhsOJvD7F66YHVQXxSwXIlnBJBaVg20tFyMZxry41kHQgaTTqmQSL/8j3Eo5kAEEnznhAGc7BQbZMBbkVk95o3Cu+24fYuEW+D0e/Gf+1RnGEA66qOXS9b+RN9wdoWHGqYzy7GwnFTwOugXFS+FxZohnr48vYexnPwpSP2b1oQOXlNFHqe4afd1nL2VcyxVW2x2L8H6j8BZ8vxZRaZnd0jJ/nXAQQXYu/a4TUxe0Mqz2S9qfVaK+xY5fcMeWHwTuOIseZvZFBwgxgvcKlEFfOTBxp1Q+0lIUYAgPfjYcxTJYNb5RgSVPpcbWyAFt+2dKfViU2PcpJ+dnFQH8sqqQ7p/wdIk09ioi0cyYF7xB0WQsW9Ik3qOnUl6jFCmRNZmYOzhBOTHEA4NNr3AYdLyTpiunbVQ2UaaB/vdg3DHHQq3Qm6DUrzqqJek1rXgnQ/G59OM="
    - PYPI_TEST_USERNAME='__token__'
    # PYPI_TEST_TOKEN
    - secure: "JAEpaTwtio8sVpv0XifCu3+LxEIenwuTni/nlGDyAghId3rh6Y9yctq+PZOlHg5hcf4r7al3TMkoAp6HGMRWsySfL//JrTdXJRAWKek/eOu45MNU6qepRY82f15gal7rVRIBKT3rcgasJoNLCGUnNwM60x3S2TyPNX6gHpC61pu8EwhLkT3gJgIwEllDh3eQ4Vnr0lupb3E4EFg3OBvfX4thoZOyV5bQs8I2UpBIrGta8PuiZJ9UmofMBhhPx9tUBHJY6FDWtO/zae0i0+XByYJrbgC/Id7d3TAlOCRTvbDeXUcTcrbHtiz9JZb9on/vCXhQX8q34RdauuqkSWJH4psGz9rU1H0BUZQdrCs2ZiID0jtWojJlkAw0SN3gWXztaG0df8Bnt33pW53GPy0xLRyJJSA6terC7wmXwy7d5XhpFMvdGC6eWb0gEylwNTWllFSuGEfWpvPlftCHTh0g8gZ0xwkQgInubjinSglT6dEiPKhWvhDRuRlV+Wr8EmQ7bY4SILGrLfyyl7kbgC2EPhQo1vi6PH4esGuvkI0RD8NqNb04xRU/iutoc186iJxbm/RGzCwXJlrWfv/eS/b/4SYg7IEx7DaOq4oolHVKxSl2F7X3GCjcLiEYzqmsO1DGIbSbd+I74LlhVfjzIWMIMKPiAZKkowy9TXXt0Yh1ztQ="
