language: python
python:
  - "3.8"
services:
  - docker
install:
  - ./scripts/setup.sh
script:
  - ./scripts/test.sh
  - ./scripts/lint.sh
  - ./scripts/build_docker.sh
  - ./scripts/test_docker.sh
after_success:
  # package and publish the library to test pypi repository
  - ./scripts/deploy.sh --test
deploy:
  # package and publish the library to pypi repository
  - provider: script
    script: ./scripts/deploy.sh
    on:
      tags: true
env:
  global:
    # DOCKER_USERNAME
    - secure: "EhBoTaKSny0A0oODcbtQJs4AGtHQ3Gi5FFiTMVIJZQPZQYSTpoCYDBujYfFItB4KEI9qy5rkLImziJ3QkNJo0qT73iaL6FVMd/JXobv6Y0UCjGOjB6mrwpuQtAeSICcpWQ62C2zztYRBHMfcCN7jIZcw9la8B5B1eYXAllUOt7VEfuTTykoWolJt3wuWb4Dy5EkjoJzkRJVBDK3i49CCxFZGoH8DZDvZ+TrFbpsrc6Ex2kRV6Fatj0B5qiQBc7GK/4Vmqf6u59v8g/zVR8pLIVCE3F8VKLIociYM9ETvam1U8OjDUJPSmu23np7tfCRM1sp6nIzchanwzcWkycu7FPGJCCGlbOPiHMD6U+JFH5gSGgicKg+9gb4I7MSRf6TiO6v4b3SAUxdY58Itgs5LGdsUOzxDLjndA8LUBNJb7vL+poKH0I/qNtlpmzjR7SZoArF63lblcrjkbP+GWlYfhpv5Fi1pkdwHjHA3CbsYnpQjO1FEo5fnyPysfDuvAYuI6zVNlZk6HnXTG3sybDCesDBSFfQKj0DRbl7p2q8s60DOV3Esoz/EEoivydq3rbDCZzF2e94/y0TuTGkKqMfGers1nx+bxuJEQluh+JyBTMW6ZFk/n9ygibBYfqzP5p+FXx1lPMIUsW/4SWjNCzxwFsWY1CdwNGCHoqDUdcUs4HM="
    # DOCKER_PASSWORD
    - secure: "iF1TvwtQr72+slS+oAL0xu0nAfyGjsuNtjZMGtt1lJDJvi7G45+7zr4fyvxWCoEShFes7ufSUlh11N7lUrYSvzleuRl2xTDE9JUSClVsX8Mlj0qhISKB3hf5v0/Fit0B3rqHwZzbnb9HSL7RJRoc0fXWGYapTs8ikHZXTBhUlz42icySEL9TW3g5PwHS8rl0sGKihVgZbbKaU7lCg1/5yNrsHL3G92guokclB/FWkoiexhR3PsnPoSQC6b/uQcRy1GT5Z6JISvpL+RFDfc6dcYk8/Gc6tXRKSM8zD/y/tyMFoJOjvOWus3/XmTkLr9qTtxcUkPS+SnY+C+o7qrE6dXqMBni8IlkeRb+THG4lubi513AsSTdQEhfGejx4ditLDn/W1ma7c51qPeNC+U8VFLzj69Z3LZHp+DYBkiHajER76Ai2CjZV0Gx8MtUlKofspYaS8nfktR8iK5cCMEy0p7E52xT9DrqKBjrfuhHeQ48IS8mPU70wCKD1DT3SQISb1znOX+7Z/xjAAH/9js1yGQuoApzuMlmk9mpTprWSrpxJyWIzOWkOn/94uUOfdGpivJfxEnpRvXLiYVsHJUleImuEaYQkYzmGFjOugT3RdacirTJ31gI7tI5gb+yeF29vqYEFgf1JnV3hTS/aWZWUdbIXZXh11LH9WStGajFulVM="
    - PYPI_USERNAME='__token__'
    # PYPI_TOKEN
    - secure: "qG/M3WKKD19G74w62qR3Kne6eO9kmZOOSEtHg3kFPIqSLIJot+I3n0Y+zqOeVfPJI8kvB6mibu290HEkdaJyJS7J3/QVPUJINFl7hfikzmVhXo+Cc4OCTLt50ydykkARbI46DmsuOG7H1vLuQVnnLVKE/OkbiAGyQccq97eCgOsw3DzpVxxzsgFbOOaB7H1vZWNE1K6xA8XhWke/M3kZTUOd1YpLZWeLovGbHNngAhsOJvD7F66YHVQXxSwXIlnBJBaVg20tFyMZxry41kHQgaTTqmQSL/8j3Eo5kAEEnznhAGc7BQbZMBbkVk95o3Cu+24fYuEW+D0e/Gf+1RnGEA66qOXS9b+RN9wdoWHGqYzy7GwnFTwOugXFS+FxZohnr48vYexnPwpSP2b1oQOXlNFHqe4afd1nL2VcyxVW2x2L8H6j8BZ8vxZRaZnd0jJ/nXAQQXYu/a4TUxe0Mqz2S9qfVaK+xY5fcMeWHwTuOIseZvZFBwgxgvcKlEFfOTBxp1Q+0lIUYAgPfjYcxTJYNb5RgSVPpcbWyAFt+2dKfViU2PcpJ+dnFQH8sqqQ7p/wdIk09ioi0cyYF7xB0WQsW9Ik3qOnUl6jFCmRNZmYOzhBOTHEA4NNr3AYdLyTpiunbVQ2UaaB/vdg3DHHQq3Qm6DUrzqqJek1rXgnQ/G59OM="
    - PYPI_TEST_USERNAME='__token__'
    # PYPI_TEST_TOKEN
    - secure: "JAEpaTwtio8sVpv0XifCu3+LxEIenwuTni/nlGDyAghId3rh6Y9yctq+PZOlHg5hcf4r7al3TMkoAp6HGMRWsySfL//JrTdXJRAWKek/eOu45MNU6qepRY82f15gal7rVRIBKT3rcgasJoNLCGUnNwM60x3S2TyPNX6gHpC61pu8EwhLkT3gJgIwEllDh3eQ4Vnr0lupb3E4EFg3OBvfX4thoZOyV5bQs8I2UpBIrGta8PuiZJ9UmofMBhhPx9tUBHJY6FDWtO/zae0i0+XByYJrbgC/Id7d3TAlOCRTvbDeXUcTcrbHtiz9JZb9on/vCXhQX8q34RdauuqkSWJH4psGz9rU1H0BUZQdrCs2ZiID0jtWojJlkAw0SN3gWXztaG0df8Bnt33pW53GPy0xLRyJJSA6terC7wmXwy7d5XhpFMvdGC6eWb0gEylwNTWllFSuGEfWpvPlftCHTh0g8gZ0xwkQgInubjinSglT6dEiPKhWvhDRuRlV+Wr8EmQ7bY4SILGrLfyyl7kbgC2EPhQo1vi6PH4esGuvkI0RD8NqNb04xRU/iutoc186iJxbm/RGzCwXJlrWfv/eS/b/4SYg7IEx7DaOq4oolHVKxSl2F7X3GCjcLiEYzqmsO1DGIbSbd+I74LlhVfjzIWMIMKPiAZKkowy9TXXt0Yh1ztQ="
