version: 2.1

orbs:
  python: circleci/python@1.2
  win: circleci/windows@2.2.0

workflows:
  build:
    jobs:
      - test-lint:
          filters:
            tags:
              ignore: /.*/
      - test-lint-docker:
          filters:
            tags:
              ignore: /.*/
      - test-lint-windows:
          filters:
            tags:
              ignore: /.*/
      - deploy-test:
          requires:
            - test-lint
            - test-lint-docker
            - test-lint-windows
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

jobs:
  test-lint:
    docker:
      - image: cimg/python:3.8
    resource_class: medium+
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-test.txt
      - run:
          name: Test
          command: scripts/test.sh
      - run:
          name: Lint
          command: scripts/lint.sh
  test-lint-docker:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Build docker
          command: scripts/build_docker.sh
      - run:
          name: Test
          command: scripts/test_docker.sh
      - run:
          name: Lint
          command: scripts/lint_docker.sh
  test-lint-windows:
    executor:
      name: win/default
      shell: bash.exe
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install requirements
          command: "pip install --user -r requirements.txt"
      - run:
          name: Install requirements for test
          command: "pip install --user -r requirements-test.txt"
      - run:
          name: Test
          command: scripts/test.sh
      - run:
          name: Lint
          command: scripts/lint.sh
  deploy-test:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-deploy.txt
      - run:
          name: Deploy (to test)
          command: scripts/deploy.sh --test
  deploy:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-deploy.txt
      - run:
          name: Deploy
          command: scripts/deploy.sh
