version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  untagged-build:
    jobs:
      - test-lint
      - deploy-test:
          filters:
            tags:
              ignore: /.*/
  tagged-build:
    jobs:
      - test-lint:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test-lint
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

jobs:
  test-lint:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Test
          command: scripts/test.sh
      - run:
          name: Lint
          command: scripts/lint.sh
  deploy-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Deploy (to test)
          command: scripts/deploy.sh --test
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Deploy
          command: scripts/deploy.sh
